# Global makefile
#
# Supported platforms:
#
#    gcc-2.95.2 (default): COMPILER=gcc
#    gcc-2.95.2-debug. . : COMPILER=gcc-debug
#    MSVC++-5(or 6). . . : COMPILER=msc
#    BCC-5.5 . . . . . . : COMPILER=bcc

ARG_PACKAGES:=arglib oxo

COMPILER=gcc

ARG_COMPILER_CFG:=makefile.$(COMPILER)
ARG_BUILD:=./build/$(COMPILER)
ARG_DEPEND:=./depend

include makefile.template

