 
// Commands (ID_* and IDM_*) 
#define HIDM_GREP_POPUP                         0x10083
#define HID_CNF_TEXT                            0x10556
#define HID_CNF_ALL                             0x1055A
#define HID_APP_SETTINGS                        0x18000
#define HID_GREP_CLEAR                          0x18004
#define HID_GREP_OPEN_FILE                      0x18005
#define HID_GREP_COLLAPSE_ALL                   0x18006
#define HID_GREP_EXPAND_ALL                     0x18007
#define HID_SQL_PREV_ERROR                      0x1801C
#define HID_SQL_HELP                            0x1801F
#define HID_SQL_ERR_HELP                        0x18020
#define HID_SQL_OBJ_VIEWER                      0x18021
#define HID_VIEW_PROPERTIES                     0x18022
#define HID_VIEW_OPEN_FILES                     0x18023
#define HID_SQL_PLAN_VIEWER                     0x18024
#define HID_CUSTOM_SPLITTER_DEF                 0x18025
#define HID_CUSTOM_SPLITTER_DOWN                0x18027
#define HID_CUSTOM_SPLITTER_UP                  0x18028
#define HID_WINDOW_CLOSE_ALL                    0x1802D
#define HID_PL_SQL_HELP                         0x18030
#define HID_SQL_DB_SOURCE                       0x18032
#define HID_VIEW_GEN_TOOLBAR                    0x1805A
#define HID_VIEW_FILE_TOOLBAR                   0x1805B
#define HID_VIEW_EDIT_TOOLBAR                   0x1805C
#define HID_VIEW_TEXT_TOOLBAR                   0x1805D
#define HID_VIEW_SQL_TOOLBAR                    0x1805E
#define HID_VIEW_SCRIPT_TOOLBAR                 0x1805F
#define HID_FILE_SHOW_GREP_OUTPUT               0x18060
#define HID_GREP_BREAK                          0x18061
#define HID_EDIT_DEL_LEFT_WORD                  0x19006
#define HID_EDIT_DEL_RIGHT_WORD                 0x19007
#define HID_EDIT_SEARCH_BRACE                   0x19008
#define HID_INDICATOR_FIRST                     0x19100
#define HID_INDICATOR_MODE                      0x19100
#define HID_INDICATOR_OCIGRID                   0x19104
#define HID_CUSTOM_NEXT_PANE                    0x19200
#define HID_CUSTOM_PREV_PANE                    0x19201
#define HID_CUSTOM_NEXT_TAB                     0x19202
#define HID_CUSTOM_PREV_TAB                     0x19203
#define HID_SQL_CONNECT                         0x19301
#define HID_SQL_DISCONNECT                      0x19302
#define HID_SQL_RECONNECT                       0x19303
#define HID_SQL_COMMIT                          0x19304
#define HID_SQL_ROLLBACK                        0x19305
#define HID_SQL_DBMS_OUTPUT                     0x19306
#define HID_SQL_EXTRACT_SCHEMA                  0x19307
#define HID_SQL_SESSION_STATISTICS              0x19308
#define HID_SQL_REFRESH_OBJECT_CACHE            0x19309
#define HID_SQL_READ_ONLY                       0x1930A
#define HID_SQL_TABLE_TRANSFORMER               0x1930B
#define HID_SQL_EXPLAIN_PLAN                    0x19408
#define HID_SQL_DESCRIBE                        0x19409
#define HID_SQL_EXECUTE                         0x1940A
#define HID_SQL_EXECUTE_FROM_CURSOR             0x1940B
#define HID_SQL_EXECUTE_CURRENT                 0x1940C
#define HID_SQL_EXECUTE_CURRENT_ALT             0x1940D
#define HID_SQL_EXECUTE_CURRENT_AND_STEP        0x1940E
#define HID_SQL_QUICK_QUERY                     0x1940F
#define HID_SQL_QUICK_COUNT                     0x19410
#define HID_SQL_SUBSTITUTION_VARIABLES          0x19411
#define HID_SQL_REFRESH                         0x19412
#define HID_SQL_NEXT_ERROR                      0x19413
#define HID_SQL_CURR_ERROR                      0x19414
#define HID_SQL_EXECUTE_IN_SQLPLUS              0x19415
#define HID_SQL_HALT_ON_ERROR                   0x19416
#define HID_ES_USE_DB_ALIAS                     0x19500
#define HID_ES_AS_DB_SCHEMA                     0x19501
#define HID_ES_AS_SCHEMA_DB                     0x19502
#define HID_ES_AS_DB_BKS_SCHEMA                 0x19503
#define HID_SQL_LOAD                            0x19505
#define HID_SQLTOOLS_ON_THE_WEB                 0x19506
#define HID_GRID_OUTPUT_EXPORT                  0x19507
#define HID_GRID_OUTPUT_OPEN                    0x19508
#define HID_GRID_OUTPUT_OPTIONS                 0x19509
#define HID_GRID_OUTPUT_EXPORT_AND_OPEN         0x1950A
#define HID_GRID_COPY_ALL                       0x1950B
#define HID_GRID_COPY_ROW                       0x1950C
#define HID_OCIGRID_DATA_FIT                    0x1950D
#define HID_OCIGRID_COLS_TO_HEADERS             0x1950E
#define HID_GRID_COPY_COL_HEADER                0x1950F
#define HID_GRID_COPY_HEADERS                   0x19510
#define HID_VIEW_CONNECT_TOOLBAR                0x19516
#define HID_BOOKLET_RESULT                      0x19517
#define HID_BOOKLET_STATISTICS                  0x19518
#define HID_BOOKLET_OUTPUT                      0x19519
#define HID_BOOKLET_HISTORY                     0x1951A
#define HID_BOOKLET_SQL_PLAN                    0x1951B
#define HID_GRID_FIST_COMMAND                   0x1951C
#define HID_GRID_ROTATE                         0x1951C
#define HID_GRID_MOVE_UP                        0x1951D
#define HID_GRID_MOVE_DOWN                      0x1951E
#define HID_GRID_MOVE_PGUP                      0x1951F
#define HID_GRID_MOVE_PGDOWN                    0x19520
#define HID_GRID_MOVE_END                       0x19521
#define HID_GRID_MOVE_HOME                      0x19522
#define HID_GRID_DATA_FIT                       0x19523
#define HID_GRID_HEADER_FIT                     0x19524
#define HID_GRID_COPY_COL                       0x19525
#define HID_GRID_SETTINGS                       0x19526
#define HID_GRID_EXPORT                         0x19527
#define HID_GRID_OPEN_WITH_IE                   0x19528
#define HID_GRID_OPEN_WITH_EXCEL                0x19529
#define HID_GRID_CLEAR_RECORDS                  0x1952A
#define HID_GRID_LAST_COMMAND                   0x1952B
#define HID_SQL_HISTORY_GET_AND_STEPBACK        0x1952E
#define HID_SQL_HISTORY_STEPFORWARD_AND_GET     0x1952F
#define HID_SQL_HISTORY_GET                     0x19530
#define HID_BOOKLET_PIN                         0x19531
#define HID_BOOKLET_UNPIN                       0x19532
#define HID_BOOKLET_BINDS                       0x19533
#define HID_BOOKLET_SQL_PLAN_TEXT               0x19534
#define HID_BOOKLET_SQL_PLAN_TREE               0x19535
#define HID_OUTPUT_TEXT_OPEN                    0x19536
#define HID_OUTPUT_TEXT_COPY                    0x19537
#define HID_CON_CONNECT                         0x1953C
#define HID_CON_TEST                            0x1953D
#define HID_CON_DELETE                          0x1953F
#define HID_CON_SETTINGS                        0x19540
#define HID_CON_COPY_USERNAME_ALIAS             0x19541
#define HID_CON_MAKE_AND_COPY_ALIAS             0x19543
#define HID_CON_CLEANUP                         0x19545
#define HID_CON_COPY_USERNAME_PASSWORD_ALIAS    0x19546
#define HID_DS_LOAD                             0x19547
#define HID_DS_LOAD_ALL_IN_ONE                  0x19548
#define HID_DS_DROP                             0x19549
#define HID_DS_COMPILE                          0x1954A
#define HID_DS_DELETE                           0x1954B
#define HID_DS_REFRESH                          0x1954C
#define HID_DS_OTHER                            0x1954D
#define HID_DS_OPTIONS                          0x1954E
#define HID_DS_ENABLE                           0x1954F
#define HID_DS_DISABLE                          0x19550
#define HID_DS_STATUS                           0x19551
#define HID_DS_FILTER                           0x19552
#define HID_DS_TAB_TITLES                       0x19553
#define HID_DS_SETTINGS                         0x19554
#define HID_DS_TRUNCATE                         0x19556
#define HID_DS_SELECT_ALL                       0x19557
#define HID_DS_FLASHBACK                        0x19558
#define HID_DS_PURGE_ALL                        0x19559
#define HID_OV_BASE                             0x1955A
#define HID_OV_REFRESH                          0x1955A
#define HID_OV_PURGE_CACHE                      0x1955B
#define HID_OV_COMPILE                          0x1955C
#define HID_OV_COPY_AS_LIST                     0x1955D
#define HID_OV_COPY_AS_COLUMN                   0x1955E
#define HID_OV_SPECIAL_COPY                     0x1955F
#define HID_OV_SETTING                          0x19560
#define HID_OV_SORT_NATURAL                     0x19561
#define HID_OV_SORT_ALPHABETICAL                0x19562
#define HID_SQL_LOAD_WITH_DBMS_METADATA         0x19563
#define HID_DS_COMPILE_ALL                      0x19564
#define HID_EXPLAIN_PLAN_ITEM_PROPERTIES        0x19565
#define HID_DS_TRANSFORM_TABLE                  0x19566
#define HID_SQL_CANCEL                          0x19567
#define HID_GRID_COPY_AS_FIRST                  0x19568
#define HID_GRID_COPY_AS_TEXT                   0x19568
#define HID_GRID_COPY_AS_PLSQL_VALUES           0x19569
#define HID_GRID_COPY_AS_PLSQL_EXPRESSION       0x1956A
#define HID_GRID_COPY_AS_PLSQL_IN_LIST          0x1956B
#define HID_GRID_COPY_AS_PLSQL_INSERTS          0x1956C
#define HID_GRID_COPY_AS_LAST                   0x1956C
#define HID_GRID_POPUP                          0x1956F
#define HID_GRIDPOPUP_TEXT                      0x19570
#define HID_GRIDPOPUP_HTML                      0x19571
#define HID_GRIDPOPUP_WORDWRAP                  0x19572
#define HID_GRIDPOPUP_CLOSE                     0x19573
#define HID_SQL_CONN_DESCRIPTION                0x19577
#define HID_FF_DIR_FIRST                        0x1C4F4
#define HID_FF_DIR_LAST                         0x1C4FD
 
// Prompts (IDP_*) 
 
// Resources (IDR_*) 
#define HIDR_MANIFEST                           0x20001
#define HIDR_MAINFRAME                          0x20080
#define HIDR_SQLTYPE                            0x20081
#define HIDR_DATA_GRID_POPUP                    0x20085
#define HIDR_GRID_POPUP                         0x20086
#define HIDR_EDIT_POPUP                         0x20087
#define HIDR_DBS_LIST_POPUP                     0x20088
#define HIDR_PLAN_POPUP                         0x20098
#define HIDR_OUTPUT_POPUP                       0x2009A
#define HIDR_ES_FOLDER_OPTIONS                  0x200A9
#define HIDR_CONNECT                            0x200BE
#define HIDR_GRIDPOPUP_OPTIONS                  0x200CD
#define HIDR_DATAGRID                           0x2012D
 
// Dialogs (IDD_*) 
#define HIDD_PROP_GRID1                         0x20065
#define HIDD_PROP_GRID2                         0x20066
#define HIDD_WAIT                               0x20082
#define HIDD_DB_SOURCE                          0x20083
#define HIDD_OBJ_INFO_TREE                      0x2008B
#define HIDD_DBS_PROP                           0x20097
#define HIDD_EXTRACT_SCHEMA                     0x20099
#define HIDD_ES_OPTION_PAGE                     0x200A3
#define HIDD_TABLE_TRANSFOMER                   0x200A5
#define HIDD_CONFIRMATION                       0x200AB
#define HIDD_CONNECT_DIALOG                     0x200AD
#define HIDD_PROP_GRID_OUTPUT                   0x200AE
#define HIDD_PROP_GRID_OUTPUT_CSV               0x200AF
#define HIDD_PROP_GRID_OUTPUT_XML               0x200B0
#define HIDD_DB_TRUNCATE                        0x200B1
#define HIDD_CONNECT_SETTINGS                   0x200BD
#define HIDD_INITIAL_SETUP                      0x200CC
#define HIDD_DFP_DIRSELECT                      0x207D0
#define HIDD_ABOUTBOX                           0x22710
#define HIDD_CONNECT                            0x22711
#define HIDD_PROP_SCRIPT                        0x2271D
#define HIDD_PROP_SERVER                        0x2271E
#define HIDD_PLAN_VIEWER                        0x22720
#define HIDD_DBS_PROP_TABLE                     0x22721
#define HIDD_FILE_FIND                          0x22723
#define HIDD_WORKBOOK_BAR                       0x22724
#define HIDD_ES_FILTER_PAGE                     0x22725
#define HIDD_ES_MAIN_PAGE                       0x22726
#define HIDD_DB_DELETE                          0x22727
#define HIDD_PROP_HISTORY                       0x22728
#define HIDD_PROP_OBJECT_VIEWER                 0x22729
 
// Frame Controls (IDW_*) 
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and related
// electronic documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.

#ifndef __AFX_HH_H__
#define __AFX_HH_H__

#pragma once

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, off)
#endif

// Non-Client HitTest help IDs
#define HID_HT_NOWHERE                          0x40000
#define HID_HT_CAPTION                          0x40002
#define HID_HT_HSCROLL                          0x40006
#define HID_HT_VSCROLL                          0x40007
#define HID_HT_MINBUTTON                        0x40008
#define HID_HT_MAXBUTTON                        0x40009
#define HID_HT_SIZE                             0x40012 // alias: ID_HT_BORDER
#define HID_HT_OBJECT							0x40013
#define HID_HT_CLOSE							0x40014
#define HID_HT_HELP								0x40015

// WM_SYSCOMMAND help IDs
#define HID_SC_SIZE                             0x1EF00
#define HID_SC_MOVE                             0x1EF01
#define HID_SC_MINIMIZE                         0x1EF02
#define HID_SC_MAXIMIZE                         0x1EF03
#define HID_SC_NEXTWINDOW                       0x1EF04
#define HID_SC_PREVWINDOW                       0x1EF05
#define HID_SC_CLOSE                            0x1EF06
#define HID_SC_RESTORE                          0x1EF12
#define HID_SC_TASKLIST                         0x1EF13

// File MRU and aliases
#define HID_FILE_MRU_FILE1                      0x1E11F

// Window menu list
#define HID_WINDOW_ALL                          0x1EF1F

// OLE menu and aliases
#define HID_OLE_VERB_1                          0x1E21F

// Commands (HID_*) 
#define HID_FILE_NEW                            0x1E100
#define HID_FILE_OPEN                           0x1E101
#define HID_FILE_CLOSE                          0x1E102
#define HID_FILE_SAVE                           0x1E103
#define HID_FILE_SAVE_AS                        0x1E104
#define HID_FILE_PAGE_SETUP                     0x1E105
#define HID_FILE_PRINT_SETUP                    0x1E106
#define HID_FILE_PRINT                          0x1E107
#define HID_FILE_PRINT_DIRECT                   0x1E108
#define HID_FILE_PRINT_PREVIEW                  0x1E109
#define HID_FILE_UPDATE                         0x1E10A
#define HID_FILE_SAVE_COPY_AS                   0x1E10B
#define HID_FILE_SEND_MAIL                      0x1E10C
#define HID_EDIT_CLEAR                          0x1E120
#define HID_EDIT_CLEAR_ALL                      0x1E121
#define HID_EDIT_COPY                           0x1E122
#define HID_EDIT_CUT                            0x1E123
#define HID_EDIT_FIND                           0x1E124
#define HID_EDIT_PASTE                          0x1E125
#define HID_EDIT_PASTE_LINK                     0x1E126
#define HID_EDIT_PASTE_SPECIAL                  0x1E127
#define HID_EDIT_REPEAT                         0x1E128
#define HID_EDIT_REPLACE                        0x1E129
#define HID_EDIT_SELECT_ALL                     0x1E12A
#define HID_EDIT_UNDO                           0x1E12B
#define HID_EDIT_REDO                           0x1E12C
#define HID_WINDOW_NEW                          0x1E130
#define HID_WINDOW_ARRANGE                      0x1E131
#define HID_WINDOW_CASCADE                      0x1E132
#define HID_WINDOW_TILE_HORZ                    0x1E133
#define HID_WINDOW_TILE_VERT                    0x1E134
#define HID_WINDOW_SPLIT                        0x1E135
#define HID_APP_ABOUT                           0x1E140
#define HID_APP_EXIT                            0x1E141
#define HID_HELP_INDEX                          0x1E142
#define HID_HELP_FINDER                         0x1E143
#define HID_HELP_USING                          0x1E144
#define HID_CONTEXT_HELP                        0x1E145
#define HID_NEXT_PANE                           0x1E150
#define HID_PREV_PANE                           0x1E151
#define HID_FORMAT_FONT                         0x1E160
#define HID_OLE_INSERT_NEW                      0x1E200
#define HID_OLE_EDIT_LINKS                      0x1E201
#define HID_OLE_EDIT_CONVERT                    0x1E202
#define HID_OLE_EDIT_CHANGE_ICON                0x1E203
#define HID_OLE_EDIT_PROPERTIES                 0x1E204
#define HID_VIEW_TOOLBAR                        0x1E800
#define HID_VIEW_STATUS_BAR                     0x1E801
#define HID_RECORD_FIRST                        0x1E900
#define HID_RECORD_LAST                         0x1E901
#define HID_RECORD_NEXT                         0x1E902
#define HID_RECORD_PREV                         0x1E903
#define HID_WIZBACK                             0x13023
#define HID_WIZNEXT                             0x13024
#define HID_WIZFINISH                           0x13025

// Dialogs (AFX_HIDD_*)
#define AFX_HIDD_FILEOPEN                       0x27004
#define AFX_HIDD_FILESAVE                       0x27005
#define AFX_HIDD_FONT                           0x27006
#define AFX_HIDD_COLOR                          0x27007
#define AFX_HIDD_PRINT                          0x27008
#define AFX_HIDD_PRINTSETUP                     0x27009
#define AFX_HIDD_FIND                           0x2700A
#define AFX_HIDD_REPLACE                        0x2700B
#define AFX_HIDD_NEWTYPEDLG                     0x27801
#define AFX_HIDD_PRINTDLG                       0x27802
#define AFX_HIDD_PREVIEW_TOOLBAR                0x27803
#define AFX_HIDD_PREVIEW_SHORTTOOLBAR           0x2780B
#define AFX_HIDD_INSERTOBJECT                   0x27804
#define AFX_HIDD_CHANGEICON                     0x27805
#define AFX_HIDD_CONVERT                        0x27806
#define AFX_HIDD_PASTESPECIAL                   0x27807
#define AFX_HIDD_EDITLINKS                      0x27808
#define AFX_HIDD_FILEBROWSE                     0x27809
#define AFX_HIDD_BUSY                           0x2780A
#define AFX_HIDD_OBJECTPROPERTIES               0x2780C
#define AFX_HIDD_CHANGESOURCE                   0x2780D

// Prompts/Errors (AFX_HIDP_*)
#define AFX_HIDP_NO_ERROR_AVAILABLE             0x3F020
#define AFX_HIDP_INVALID_FILENAME               0x3F100
#define AFX_HIDP_FAILED_TO_OPEN_DOC             0x3F101
#define AFX_HIDP_FAILED_TO_SAVE_DOC             0x3F102
#define AFX_HIDP_ASK_TO_SAVE                    0x3F103
#define AFX_HIDP_FAILED_TO_CREATE_DOC           0x3F104
#define AFX_HIDP_FILE_TOO_LARGE                 0x3F105
#define AFX_HIDP_FAILED_TO_START_PRINT          0x3F106
#define AFX_HIDP_FAILED_TO_LAUNCH_HELP          0x3F107
#define AFX_HIDP_INTERNAL_FAILURE               0x3F108
#define AFX_HIDP_COMMAND_FAILURE                0x3F109
#define AFX_HIDP_FAILED_MEMORY_ALLOC            0x3F10A
#define AFX_HIDP_UNREG_DONE                     0x3F10B
#define AFX_HIDP_UNREG_FAILURE                  0x3F10C
#define AFX_HIDP_DLL_LOAD_FAILED                0x3F10D
#define AFX_HIDP_DLL_BAD_VERSION                0x3F10E
#define AFX_HIDP_PARSE_INT                      0x3F110
#define AFX_HIDP_PARSE_REAL                     0x3F111
#define AFX_HIDP_PARSE_INT_RANGE                0x3F112
#define AFX_HIDP_PARSE_REAL_RANGE               0x3F113
#define AFX_HIDP_PARSE_STRING_SIZE              0x3F114
#define AFX_HIDP_PARSE_RADIO_BUTTON             0x3F115
#define AFX_HIDP_PARSE_BYTE                     0x3F116
#define AFX_HIDP_PARSE_UINT                     0x3F117
#define AFX_HIDP_PARSE_DATETIME                 0x3F118
#define AFX_HIDP_PARSE_CURRENCY                 0x3F119
#define AFX_HIDP_FAILED_INVALID_FORMAT          0x3F120
#define AFX_HIDP_FAILED_INVALID_PATH            0x3F121
#define AFX_HIDP_FAILED_DISK_FULL               0x3F122
#define AFX_HIDP_FAILED_ACCESS_READ             0x3F123
#define AFX_HIDP_FAILED_ACCESS_WRITE            0x3F124
#define AFX_HIDP_FAILED_IO_ERROR_READ           0x3F125
#define AFX_HIDP_FAILED_IO_ERROR_WRITE          0x3F126
#define AFX_HIDP_STATIC_OBJECT                  0x3F180
#define AFX_HIDP_FAILED_TO_CONNECT              0x3F181
#define AFX_HIDP_SERVER_BUSY                    0x3F182
#define AFX_HIDP_BAD_VERB                       0x3F183
#define AFX_HIDP_FAILED_TO_NOTIFY               0x3F185
#define AFX_HIDP_FAILED_TO_LAUNCH               0x3F186
#define AFX_HIDP_ASK_TO_UPDATE                  0x3F187
#define AFX_HIDP_FAILED_TO_UPDATE               0x3F188
#define AFX_HIDP_FAILED_TO_REGISTER             0x3F189
#define AFX_HIDP_FAILED_TO_AUTO_REGISTER        0x3F18A
#define AFX_HIDP_FAILED_TO_CONVERT              0x3F18B
#define AFX_HIDP_GET_NOT_SUPPORTED              0x3F18C
#define AFX_HIDP_SET_NOT_SUPPORTED              0x3F18D
#define AFX_HIDP_ASK_TO_DISCARD                 0x3F18E
#define AFX_HIDP_FAILED_TO_CREATE               0x3F18F
#define AFX_HIDP_FAILED_MAPI_LOAD               0x3F190
#define AFX_HIDP_INVALID_MAPI_DLL               0x3F191
#define AFX_HIDP_FAILED_MAPI_SEND               0x3F192
#define AFX_HIDP_FILE_NONE                      0x3F1A0
#define AFX_HIDP_FILE_GENERIC                   0x3F1A1
#define AFX_HIDP_FILE_NOT_FOUND                 0x3F1A2
#define AFX_HIDP_FILE_BAD_PATH                  0x3F1A3
#define AFX_HIDP_FILE_TOO_MANY_OPEN             0x3F1A4
#define AFX_HIDP_FILE_ACCESS_DENIED             0x3F1A5
#define AFX_HIDP_FILE_INVALID_FILE              0x3F1A6
#define AFX_HIDP_FILE_REMOVE_CURRENT            0x3F1A7
#define AFX_HIDP_FILE_DIR_FULL                  0x3F1A8
#define AFX_HIDP_FILE_BAD_SEEK                  0x3F1A9
#define AFX_HIDP_FILE_HARD_IO                   0x3F1AA
#define AFX_HIDP_FILE_SHARING                   0x3F1AB
#define AFX_HIDP_FILE_LOCKING                   0x3F1AC
#define AFX_HIDP_FILE_DISKFULL                  0x3F1AD
#define AFX_HIDP_FILE_EOF                       0x3F1AE
#define AFX_HIDP_ARCH_NONE                      0x3F1B0
#define AFX_HIDP_ARCH_GENERIC                   0x3F1B1
#define AFX_HIDP_ARCH_READONLY                  0x3F1B2
#define AFX_HIDP_ARCH_ENDOFFILE                 0x3F1B3
#define AFX_HIDP_ARCH_WRITEONLY                 0x3F1B4
#define AFX_HIDP_ARCH_BADINDEX                  0x3F1B5
#define AFX_HIDP_ARCH_BADCLASS                  0x3F1B6
#define AFX_HIDP_ARCH_BADSCHEMA                 0x3F1B7
#define AFX_HIDP_SQL_CONNECT_FAIL               0x3F281
#define AFX_HIDP_SQL_RECORDSET_FORWARD_ONLY     0x3F282
#define AFX_HIDP_SQL_EMPTY_COLUMN_LIST          0x3F283
#define AFX_HIDP_SQL_FIELD_SCHEMA_MISMATCH      0x3F284
#define AFX_HIDP_SQL_ILLEGAL_MODE               0x3F285
#define AFX_HIDP_SQL_MULTIPLE_ROWS_AFFECTED     0x3F286
#define AFX_HIDP_SQL_NO_CURRENT_RECORD          0x3F287
#define AFX_HIDP_SQL_NO_ROWS_AFFECTED           0x3F288
#define AFX_HIDP_SQL_RECORDSET_READONLY         0x3F289
#define AFX_HIDP_SQL_SQL_NO_TOTAL               0x3F28A
#define AFX_HIDP_SQL_ODBC_LOAD_FAILED           0x3F28B
#define AFX_HIDP_SQL_DYNASET_NOT_SUPPORTED      0x3F28C
#define AFX_HIDP_SQL_SNAPSHOT_NOT_SUPPORTED     0x3F28D
#define AFX_HIDP_SQL_API_CONFORMANCE            0x3F28E
#define AFX_HIDP_SQL_SQL_CONFORMANCE            0x3F28F
#define AFX_HIDP_SQL_NO_DATA_FOUND              0x3F290
#define AFX_HIDP_SQL_ROW_UPDATE_NOT_SUPPORTED   0x3F291
#define AFX_HIDP_SQL_ODBC_V2_REQUIRED           0x3F292
#define AFX_HIDP_SQL_NO_POSITIONED_UPDATES      0x3F293
#define AFX_HIDP_SQL_LOCK_MODE_NOT_SUPPORTED    0x3F294
#define AFX_HIDP_SQL_DATA_TRUNCATED             0x3F295
#define AFX_HIDP_SQL_ROW_FETCH                  0x3F296
#define AFX_HIDP_SQL_INCORRECT_ODBC             0x3F297
#define AFX_HIDP_SQL_UPDATE_DELETE_FAILED       0x3F298
#define AFX_HIDP_SQL_DYNAMIC_CURSOR_NOT_SUPPORTED	0x3F299
#define AFX_HIDP_SQL_FIELD_NOT_FOUND            0x3F29A
#define AFX_HIDP_SQL_BOOKMARKS_NOT_SUPPORTED    0x3F29B
#define AFX_HIDP_SQL_BOOKMARKS_NOT_ENABLED      0x3F29C
#define AFX_HIDP_DAO_ENGINE_INITIALIZATION      0x3F2B0
#define AFX_HIDP_DAO_DFX_BIND                   0x3F2B1
#define AFX_HIDP_DAO_OBJECT_NOT_OPEN            0x3F2B2
#define AFX_HIDP_DAO_ROWTOOSHORT                0x3F2B3
#define AFX_HIDP_DAO_BADBINDINFO                0x3F2B4
#define AFX_HIDP_DAO_COLUMNUNAVAILABLE          0x3F2B5

// Frame Controls (AFX_HIDW_*)
#define AFX_HIDW_TOOLBAR                        0x5E800
#define AFX_HIDW_STATUS_BAR                     0x5E801
#define AFX_HIDW_PREVIEW_BAR                    0x5E802
#define AFX_HIDW_RESIZE_BAR                     0x5E803
#define AFX_HIDW_DOCKBAR_TOP                    0x5E81B
#define AFX_HIDW_DOCKBAR_LEFT                   0x5E81C
#define AFX_HIDW_DOCKBAR_RIGHT                  0x5E81D
#define AFX_HIDW_DOCKBAR_BOTTOM                 0x5E81E
#define AFX_HIDW_DOCKBAR_FLOAT                  0x5E81F

/////////////////////////////////////////////////////////////////////////////

#ifdef _AFX_MINREBUILD
#pragma component(minrebuild, on)
#endif

#endif // __AFX_HH_H__
 
// Resources (IDR_*) 
#define HIDR_OPENEDITOR                         0x20515
#define HIDR_OE_CBAR_POPUP                      0x20516
#define HIDR_OE_DRIVERS_POPUP                   0x20517
#define HIDR_OE_EDIT_POPUP                      0x20518
#define HIDR_OE_EXPLORER_POPUP                  0x20519
#define HIDR_OE_REGEXP_FIND_POPUP               0x2051A
#define HIDR_OE_REGEXP_REPLACE_POPUP            0x2051B
#define HIDR_OE_WORKBOOK_POPUP                  0x2051C
 
// Dialogs (IDD_*) 
#define HIDD_INPUT                              0x20579
#define HIDD_INPUT_PASSWORD                     0x2057A
#define HIDD_OE_ABOUTBOX                        0x2057B
#define HIDD_OE_EDIT_FIND                       0x2057C
#define HIDD_OE_EDIT_REPLACE                    0x2057D
#define HIDD_OE_BACKUP                          0x2057E
#define HIDD_OE_BLOCKS                          0x2057F
#define HIDD_OE_CLASSES                         0x20580
#define HIDD_OE_EDITING                         0x20581
#define HIDD_OE_FILES                           0x20582
#define HIDD_OE_FILE_INFO                       0x20583
#define HIDD_OE_FILE_SETTINGS                   0x20584
#define HIDD_OE_GENERAL                         0x20585
#define HIDD_OE_GOTO                            0x20586
#define HIDD_OE_TEMPLATES                       0x20587
#define HIDD_OE_TEMPLATE_FORM                   0x20588
#define HIDD_OE_PRINT_PAGE_SETUP                0x20589
#define HIDD_OE_PROP_FONT_COLORS                0x2058A
#define HIDD_OE_WORKBOOK_BAR                    0x2058B
#define HIDD_OE_SAVE_ALL                        0x2058C
#define HIDD_ERROR                              0x2058D
#define HIDD_OE_SORT                            0x2058E
#define HIDD_OE_OVERWRITE_FILE                  0x2058F
#define HIDD_OE_NEW_FILE                        0x20590
#define HIDD_OE_FILE_MANAGER                    0x20591
#define HIDD_OE_COLUMN_NUMBER                   0x20592
#define HIDD_OE_SPLIT_LINES                     0x20593
#define HIDD_OE_WORKSPACE                       0x20594
 
// Commands (ID_* and IDM_*) 
#define HID_TEST                                0x1C350
#define HID_CBAR_DOCKING                        0x1C351
#define HID_CBAR_HIDE                           0x1C352
#define HID_EDIT_BKM_GET_0                      0x1C353
#define HID_EDIT_BKM_GET_1                      0x1C354
#define HID_EDIT_BKM_GET_2                      0x1C355
#define HID_EDIT_BKM_GET_3                      0x1C356
#define HID_EDIT_BKM_GET_4                      0x1C357
#define HID_EDIT_BKM_GET_5                      0x1C358
#define HID_EDIT_BKM_GET_6                      0x1C359
#define HID_EDIT_BKM_GET_7                      0x1C35A
#define HID_EDIT_BKM_GET_8                      0x1C35B
#define HID_EDIT_BKM_GET_9                      0x1C35C
#define HID_EDIT_BKM_NEXT                       0x1C35D
#define HID_EDIT_BKM_PREV                       0x1C35E
#define HID_EDIT_BKM_REMOVE_ALL                 0x1C35F
#define HID_EDIT_BKM_SET_0                      0x1C360
#define HID_EDIT_BKM_SET_1                      0x1C361
#define HID_EDIT_BKM_SET_2                      0x1C362
#define HID_EDIT_BKM_SET_3                      0x1C363
#define HID_EDIT_BKM_SET_4                      0x1C364
#define HID_EDIT_BKM_SET_5                      0x1C365
#define HID_EDIT_BKM_SET_6                      0x1C366
#define HID_EDIT_BKM_SET_7                      0x1C367
#define HID_EDIT_BKM_SET_8                      0x1C368
#define HID_EDIT_BKM_SET_9                      0x1C369
#define HID_EDIT_BKM_TOGGLE                     0x1C36A
#define HID_EDIT_CAPITALIZE                     0x1C36B
#define HID_EDIT_STREAM_SEL                     0x1C36C
#define HID_EDIT_COLUMN_SEL                     0x1C36D
#define HID_EDIT_COPY_BOOKMARKED                0x1C36E
#define HID_EDIT_COPY_N_APPEND                  0x1C36F
#define HID_EDIT_CUT_BOOKMARKED                 0x1C370
#define HID_EDIT_CUT_N_APPEND                   0x1C371
#define HID_EDIT_DATETIME_STAMP                 0x1C372
#define HID_EDIT_DELETE                         0x1C373
#define HID_EDIT_DELETE_BOOKMARKED              0x1C374
#define HID_EDIT_DELETE_LINE                    0x1C375
#define HID_EDIT_DELETE_WORD_TO_LEFT            0x1C376
#define HID_EDIT_DELETE_WORD_TO_RIGHT           0x1C377
#define HID_EDIT_EXPAND_TEMPLATE                0x1C378
#define HID_EDIT_FILE_SETTINGS                  0x1C379
#define HID_EDIT_FIND_MATCH                     0x1C37A
#define HID_EDIT_FIND_MATCH_N_SELECT            0x1C37B
#define HID_EDIT_FIND_NEXT                      0x1C37C
#define HID_EDIT_FIND_PREVIOUS                  0x1C37D
#define HID_EDIT_FIND_SELECTED_NEXT             0x1C37E
#define HID_EDIT_FIND_SELECTED_PREVIOUS         0x1C37F
#define HID_EDIT_GOTO                           0x1C380
#define HID_EDIT_GO_LINE                        0x1C381
#define HID_EDIT_INDENT                         0x1C382
#define HID_EDIT_INVERT_CASE                    0x1C383
#define HID_EDIT_LOWER                          0x1C384
#define HID_EDIT_NEXT                           0x1C385
#define HID_EDIT_NORMALIZE_TEXT                 0x1C386
#define HID_EDIT_PERMANENT_SETTINGS             0x1C387
#define HID_EDIT_PREVIOUS                       0x1C388
#define HID_EDIT_PRINT_PAGE_SETUP               0x1C389
#define HID_EDIT_SCROLL_CENTER                  0x1C38A
#define HID_EDIT_SCROLL_DOWN                    0x1C38B
#define HID_EDIT_SCROLL_UP                      0x1C38C
#define HID_EDIT_SELECT_LINE                    0x1C38D
#define HID_EDIT_SELECT_WORD                    0x1C38E
#define HID_EDIT_SORT                           0x1C38F
#define HID_EDIT_COMMENT                        0x1C390
#define HID_EDIT_TABIFY                         0x1C391
#define HID_EDIT_TABIFY_LEADING                 0x1C392
#define HID_EDIT_TOGGLES_SEL                    0x1C393
#define HID_EDIT_UNCOMMENT                      0x1C394
#define HID_EDIT_UNDENT                         0x1C395
#define HID_EDIT_UNTABIFY                       0x1C396
#define HID_EDIT_UPPER                          0x1C397
#define HID_EDIT_VIEW_LINE_NUMBERS              0x1C398
#define HID_EDIT_VIEW_WHITE_SPACE               0x1C399
#define HID_EDIT_VIEW_SYNTAX_GUTTER             0x1C39A
#define HID_FILE_NEW_EXT                        0x1C39B
#define HID_FILE_CLOSE_ALL                      0x1C39C
#define HID_FILE_CLOSE_OTHERS                   0x1C39D
#define HID_FILE_FIND_IN_FILE                   0x1C39E
#define HID_FILE_RELOAD                         0x1C39F
#define HID_FILE_SAVE_ALL                       0x1C3A0
#define HID_FILE_SYNC_LOCATION                  0x1C3A1
#define HID_FILE_COPY_LOCATION                  0x1C3A2
#define HID_FILE_RENAME                         0x1C3A3
#define HID_EDIT_CREATE_TEMPLATE                0x1C3A4
#define HID_FILE_COPY_NAME                      0x1C3A5
#define HID_FPW_REFRESH_DRIVERS                 0x1C3B4
#define HID_FPW_OPEN                            0x1C3B5
#define HID_FPW_SHELL_OPEN                      0x1C3B6
#define HID_FPW_RENAME                          0x1C3B7
#define HID_FPW_DELETE                          0x1C3B8
#define HID_FPW_REFRESH                         0x1C3B9
#define HID_FPW_HISTORY_OPEN                    0x1C3BA
#define HID_FPW_HISTORY_REMOVE                  0x1C3BB
#define HID_VIEW_FILE_PANEL                     0x1C3BC
#define HID_VIEW_HISTORY                        0x1C3BD
#define HID_WINDOW_LAST                         0x1C3BE
#define HID_APP_ON_THE_WEB                      0x1C3BF
#define HID_EDIT_VIEW_RULER                     0x1C3C0
#define HID_EDIT_VIEW_COLUMN_MARKERS            0x1C3C1
#define HID_EDIT_OPENFILEUNDERCURSOR            0x1C3C2
#define HID_EDIT_VIEW_INDENT_GUIDE              0x1C3C3
#define HID_INDICATOR_BLOCK_TYPE                0x1C3C4
#define HID_INDICATOR_FILE_LINES                0x1C3C5
#define HID_INDICATOR_FILE_TYPE                 0x1C3C6
#define HID_INDICATOR_LINE                      0x1C3C7
#define HID_INDICATOR_MODIFIED                  0x1C3C8
#define HID_INDICATOR_POS                       0x1C3C9
#define HID_INDICATOR_SCROLL_POS                0x1C3CA
#define HID_INDICATOR_CUR_CHAR                  0x1C3CB
#define HID_INDICATOR_WORKSPACE_NAME            0x1C3CC
#define HID_FILEPANE_EXPLORER                   0x1C3D1
#define HID_FILEPANE_OPEN_FILES                 0x1C3D2
#define HID_APP_SETTINGS_FOLDER                 0x1C3D3
#define HID_INDICATOR_ENCODING                  0x1C3D5
#define HID_EDIT_COLUMN_INSERT_FILL             0x1C3E7
#define HID_EDIT_COLUMN_INSERT_NUMBER           0x1C3E8
#define HID_EDIT_COLUMN_SUM                     0x1C3E9
#define HID_EDIT_COLUMN_LEFT_JUSTIFY            0x1C3EA
#define HID_EDIT_COLUMN_RIGT_JUSTIFY            0x1C3EB
#define HID_EDIT_COLUMN_CENTER_JUSTIFY          0x1C3EC
#define HID_EDIT_COLUMN_CONVERT_TO_FIX          0x1C3ED
#define HID_EDIT_COLUMN_CONVERT_TO_CSV          0x1C3EE
#define HID_EDIT_FORMAT_JOIN_LINES              0x1C3F0
#define HID_EDIT_FORMAT_SPLIT_LINES             0x1C3F1
#define HID_EDIT_FORMAT_REMOVE_BLANK            0x1C3F2
#define HID_EDIT_FORMAT_REMOVE_EXCESSIVE_BLANK  0x1C3F3
#define HID_EDIT_FORMAT_TRIM_LEADING_SPACES     0x1C3F4
#define HID_EDIT_FORMAT_TRIM_EXCESSIVE_SPACES   0x1C3F5
#define HID_EDIT_FORMAT_TRIM_TRAILING_SPACES    0x1C3F6
#define HID_EDIT_AUTOCOMPLETE                   0x1C3F7
#define HID_EDIT_DUP_LINE_OR_SELECTION          0x1C3F8
#define HID_EDIT_FILE_FORMAT_WINOWS             0x1C3F9
#define HID_EDIT_FILE_FORMAT_UNIX               0x1C3FA
#define HID_EDIT_FILE_FORMAT_MAC                0x1C3FB
#define HID_EDIT_ENCODING_ANSI                  0x1C3FC
#define HID_EDIT_ENCODING_OEM                   0x1C3FD
#define HID_EDIT_ENCODING_UTF8                  0x1C3FE
#define HID_FILE_ENCODING_ANSI                  0x1C3FF
#define HID_FILE_ENCODING_OEM                   0x1C400
#define HID_FILE_ENCODING_UTF8                  0x1C401
#define HID_FILE_ENCODING_UTF8_BOM              0x1C402
#define HID_FILE_ENCODING_UTF16_BOM             0x1C403
#define HID_EDIT_ENCODING_CODEPAGE_FIRST        0x1C418
#define HID_EDIT_ENCODING_CODEPAGE_LAST         0x1C449
#define HID_FILE_ENCODING_CODEPAGE_FIRST        0x1C44A
#define HID_FILE_ENCODING_CODEPAGE_LAST         0x1C47B
#define HID_REGEXP_FIND_TAB                     0x1C47D
#define HID_REGEXP_FIND_ANY_CHAR                0x1C47E
#define HID_REGEXP_FIND_ZERO_OR_MORE            0x1C47F
#define HID_REGEXP_FIND_ONE_OR_MORE             0x1C480
#define HID_REGEXP_FIND_BOL                     0x1C481
#define HID_REGEXP_FIND_EOL                     0x1C482
#define HID_REGEXP_FIND_SET                     0x1C483
#define HID_REGEXP_FIND_NOT_SET                 0x1C484
#define HID_REGEXP_FIND_OR                      0x1C485
#define HID_REGEXP_FIND_ESC                     0x1C486
#define HID_REGEXP_FIND_ALNUM                   0x1C487
#define HID_REGEXP_FIND_ALPHA                   0x1C488
#define HID_REGEXP_FIND_DIGIT                   0x1C489
#define HID_REGEXP_FIND_XDIGIT                  0x1C48A
#define HID_REGEXP_FIND_IDENTIFIER              0x1C48B
#define HID_REGEXP_FIND_RATIONAL                0x1C48C
#define HID_REGEXP_FIND_QUOTED                  0x1C48D
#define HID_REGEXP_REPLACE_WHAT_FIND            0x1C4AF
#define HID_REGEXP_REPLACE_TAGEXP_1             0x1C4B0
#define HID_REGEXP_REPLACE_TAGEXP_2             0x1C4B1
#define HID_REGEXP_REPLACE_TAGEXP_3             0x1C4B2
#define HID_REGEXP_REPLACE_TAGEXP_4             0x1C4B3
#define HID_REGEXP_REPLACE_TAGEXP_5             0x1C4B4
#define HID_REGEXP_REPLACE_TAGEXP_6             0x1C4B5
#define HID_REGEXP_REPLACE_TAGEXP_7             0x1C4B6
#define HID_REGEXP_REPLACE_TAGEXP_8             0x1C4B7
#define HID_REGEXP_REPLACE_TAGEXP_9             0x1C4B8
#define HID_WORKSPACE_COPY                      0x1C4B9
#define HID_WORKSPACE_PASTE                     0x1C4BA
#define HID_WORKSPACE_SAVE                      0x1C4BB
#define HID_WORKSPACE_SAVE_AS                   0x1C4BC
#define HID_WORKSPACE_SAVE_QUICK                0x1C4BD
#define HID_WORKSPACE_OPEN                      0x1C4BE
#define HID_WORKSPACE_OPEN_QUICK                0x1C4BF
#define HID_WORKSPACE_OPEN_AUTOSAVED            0x1C4C0
#define HID_WORKSPACE_CLOSE                     0x1C4C1
#define HID_WORKSPACE_MRU_FIRST                 0x1C4C2
#define HID_WORKSPACE_MRU_FILE1                 0x1C4C2
#define HID_WORKSPACE_MRU_FILE2                 0x1C4C3
#define HID_WORKSPACE_MRU_FILE3                 0x1C4C4
#define HID_WORKSPACE_MRU_FILE4                 0x1C4C5
#define HID_WORKSPACE_MRU_FILE5                 0x1C4C6
#define HID_WORKSPACE_MRU_FILE6                 0x1C4C7
#define HID_WORKSPACE_MRU_FILE7                 0x1C4C8
#define HID_WORKSPACE_MRU_FILE8                 0x1C4C9
#define HID_WORKSPACE_MRU_FILE9                 0x1C4CA
#define HID_WORKSPACE_MRU_FILE10                0x1C4CB
#define HID_WORKSPACE_MRU_FILE11                0x1C4CC
#define HID_WORKSPACE_MRU_FILE12                0x1C4CD
#define HID_WORKSPACE_MRU_FILE13                0x1C4CE
#define HID_WORKSPACE_MRU_FILE14                0x1C4CF
#define HID_WORKSPACE_MRU_FILE15                0x1C4D0
#define HID_WORKSPACE_MRU_FILE16                0x1C4D1
#define HID_WORKSPACE_MRU_LAST                  0x1C4D1
#define HID_WORKSPACE_QUICK_MRU_FIRST           0x1C4D6
#define HID_WORKSPACE_QUICK_MRU_FILE1           0x1C4D6
#define HID_WORKSPACE_QUICK_MRU_FILE2           0x1C4D7
#define HID_WORKSPACE_QUICK_MRU_FILE3           0x1C4D8
#define HID_WORKSPACE_QUICK_MRU_FILE4           0x1C4D9
#define HID_WORKSPACE_QUICK_MRU_FILE5           0x1C4DA
#define HID_WORKSPACE_QUICK_MRU_FILE6           0x1C4DB
#define HID_WORKSPACE_QUICK_MRU_FILE7           0x1C4DC
#define HID_WORKSPACE_QUICK_MRU_FILE8           0x1C4DD
#define HID_WORKSPACE_QUICK_MRU_FILE9           0x1C4DE
#define HID_WORKSPACE_QUICK_MRU_FILE10          0x1C4DF
#define HID_WORKSPACE_QUICK_MRU_FILE11          0x1C4E0
#define HID_WORKSPACE_QUICK_MRU_FILE12          0x1C4E1
#define HID_WORKSPACE_QUICK_MRU_FILE13          0x1C4E2
#define HID_WORKSPACE_QUICK_MRU_FILE14          0x1C4E3
#define HID_WORKSPACE_QUICK_MRU_FILE15          0x1C4E4
#define HID_WORKSPACE_QUICK_MRU_FILE16          0x1C4E5
#define HID_WORKSPACE_QUICK_MRU_LAST            0x1C4E5
#define HID_APP_DBLKEYACCEL_FIRST               0x1DF00
#define HID_APP_DBLKEYACCEL_LAST                0x1DFFF
#define HID_WINDOW_PREV                         0x1C4EA
#define HID_WINDOW_NEXT                         0x1C4EB
