rem /connect=scott/tiger@192.168.56.1:1521:soadb E:\_CPP\sqlt.20\TestFiles\current.sql

var n NUMBER
EXEC :n := 1.9999;
var d date
EXEC :d := sysdate


--/connect=scott/tiger@192.168.56.1:1521:soadb E:\_CPP\sqlt.19\TestFiles\current.sql
SELECT * FROM pt_range;
SELECT * FROM quarterly_regional_sales;

INSERT INTO pt_range VALUES(DATE'1999-03-01', 1, '?');
INSERT INTO pt_range VALUES(DATE'1999-03-01', 2, '?');
INSERT INTO pt_range VALUES(DATE'1999-03-01', 3, '?');
INSERT INTO pt_range VALUES(DATE'1999-04-02', 1, '?');
INSERT INTO pt_range VALUES(DATE'1999-04-02', 2, '?');
INSERT INTO pt_range VALUES(DATE'1999-04-02', 3, '?');

SELECT * FROM pt_range partition (SMPL_01APR1999_1);
SELECT * FROM pt_range partition (SMPL_01APR1999_2);
SELECT * FROM pt_range partition (SMPL_01APR1999_REST);
SELECT * FROM pt_range partition (SMPL_02APR1999_1);
SELECT * FROM pt_range partition (SMPL_02APR1999_2);
SELECT * FROM pt_range partition (SMPL_02APR1999_REST);


SELECT NULL char_col, To_Number(NULL) num_col, To_Date(NULL) date_col  FROM dual
UNION ALL
SELECT 'xxx', -1, SYSDATE FROM dual;
/

BEGIN
  FOR i IN 1..1000 LOOP
     Dbms_Output.Put_Line(RPad(LPad('hi', 100, '!'), 202, '!'));
  END LOOP;
END;
/

CREATE SEQUENCE test_seq;
DROP TABLE test;
CREATE TABLE test (
  --key NUMBER(12) GENERATED BY DEFAULT AS IDENTITY
  key NUMBER(12) GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
);

CREATE TABLE test4 (
  key NUMBER(12) GENERATED ALWAYS AS IDENTITY
  --key NUMBER(12) GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
);

SELECT seq.*, obj.generated FROM all_sequences seq, all_objects obj
  WHERE seq.sequence_owner = 'SCOTT'
    AND seq.sequence_owner = obj.owner
    AND seq.sequence_name = obj.object_name
/

SELECT
    seq.sequence_owner,
    seq.sequence_name,
    seq.min_value,
    seq.max_value,
    seq.increment_by,
    seq.cycle_flag,
    seq.order_flag,
    seq.cache_size,
    seq.last_number,
    obj.generated
  FROM all_sequences seq, all_objects obj
    WHERE seq.sequence_owner = 'SCOTT'
      AND seq.sequence_owner = obj.owner
      AND seq.sequence_name = obj.object_name
      AND (sequence_owner, sequence_name)
        IN (
          SELECT owner, sequence_name
            FROM all_tab_identity_cols
              WHERE owner = 'SCOTT'
                AND table_name = 'TEST'
        )
/
SELECT
  owner, table_name, column_name, generation_type, sequence_name, identity_options
FROM all_tab_identity_cols;

SELECT * FROM user_objects WHERE generated = 'Y';
SELECT * FROM user_sequences;
SELECT * FROM user_tab_columns WHERE table_name = 'TEST';
SELECT * FROM all_tab_cols WHERE table_name = 'TEST';
--identity_column = 'YES'
SELECT * FROM user_tab_identity_cols;

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

CONNECT sys/kolobok@w2k-10g:1521:test10 AS SYSDBA

SELECT '<HTML> <HEAD> <TITLE>Your Title Here</TITLE> </HEAD> <BODY BGCOLOR="FFFFFF"> <CENTER><IMG SRC="clouds.jpg" ALIGN="BOTTOM"> </CENTER> <HR> <a href="http://somegreatsite.com">Link Name (алоывапрло)</a> is a link to another nifty site <H1>This is a Header</H1> <H2>This is a Medium Header</H2> Send me mail at <a href="mailto:support@yourcompany.com"> support@yourcompany.com</a>. <P> This is a new paragraph! <P> <B>This is a new paragraph!</B> <BR> <B><I>This is a new sentence without a paragraph break, in bold italics.</I></B> <HR> </BODY> </HTML>' FROM dual;
SELECT '<?xml version="1.0" standalone="yes"?><svg width="1in" height="1in"><desc></desc><g class="line" style="fill:#33a9ff;stroke-width:4"><line class="parallel" style="fill:#aa55cc;stroke-width:1.0" /></g></svg>' FROM dual;
SELECT '<?xml version="1.0" standalone="yes"?>
<svg width="1in" height="1in">
<desc></desc>
<g class="line" style="fill:#33a9ff;stroke-width:4">
<line class="parallel" style="fill:#aa55cc;stroke-width:1.0" />
</g>
</svg>' FROM dual;


SELECT * FROM all_sdo_styles;
SELECT definition FROM all_sdo_styles WHERE ROWNUM < 2;

BEGIN
  SELECT 'рол' xxx FROM dual;
END;
/
SELECT t.*, 'рол' FROM emp t;
EXEC Dbms_Lock.sleep(seconds => 20);

SELECT SYSDATE FROM dual;
SELECT 'test '' test', current_timestamp FROM dual;
SELECT 'test '' test', To_Timestamp_TZ('27.11.2017 17:05:58.831 -05:00', 'dd.mm.yyyy hh24:mi:ss.ff3 tzr') FROM dual;
SELECT 'test '' test', current_timestamp - To_Timestamp_TZ('27.11.2017 17:05:58.831 -05:00', 'dd.mm.yyyy hh24:mi:ss.ff3 tzr') FROM dual;

-- drag & drop
MANAGER 7839 1981-06-09 00:00:00
MANAGER 7839 1981-04-02 00:00:00
ANALYST 7566 1987-04-19 00:00:00
ANALYST 7566 1981-12-03 00:00:00

-- drag & drop with <Shift> pressed
  'MANAGER', 7839, To_Date('1981-06-09 00:00:00', 'yyyy-mm-dd hh24:mi:ss')
  'MANAGER', 7839, To_Date('1981-04-02 00:00:00', 'yyyy-mm-dd hh24:mi:ss')
  'ANALYST', 7566, To_Date('1987-04-19 00:00:00', 'yyyy-mm-dd hh24:mi:ss')
  'ANALYST', 7566, To_Date('1981-12-03 00:00:00', 'yyyy-mm-dd hh24:mi:ss')

-- drag & drop with <Ctrl> pressed
    job = 'MANAGER' AND mgr = 7839 AND hiredate = To_Date('1981-06-09 00:00:00', 'yyyy-mm-dd hh24:mi:ss')
    job = 'MANAGER' AND mgr = 7839 AND hiredate = To_Date('1981-04-02 00:00:00', 'yyyy-mm-dd hh24:mi:ss')
    job = 'ANALYST' AND mgr = 7566 AND hiredate = To_Date('1987-04-19 00:00:00', 'yyyy-mm-dd hh24:mi:ss')
    job = 'ANALYST' AND mgr = 7566 AND hiredate = To_Date('1981-12-03 00:00:00', 'yyyy-mm-dd hh24:mi:ss')

-- drag & drop with both <Shift> and <Ctrl> pressed
      (job, mgr, hiredate)
      IN
      (
        ('MANAGER', 7839, To_Date('1981-06-09 00:00:00', 'yyyy-mm-dd hh24:mi:ss')),
        ('MANAGER', 7839, To_Date('1981-04-02 00:00:00', 'yyyy-mm-dd hh24:mi:ss')),
        ('ANALYST', 7566, To_Date('1987-04-19 00:00:00', 'yyyy-mm-dd hh24:mi:ss')),
        ('ANALYST', 7566, To_Date('1981-12-03 00:00:00', 'yyyy-mm-dd hh24:mi:ss'))
      )